### ISSUE TITLE
Neet a windows *.bat file 

### ISSUE THREAD

**Issue by chenjianjx** [chenjianjx/swagger2html#1]
Can anybody help?

**Comment by dp-la** [comment]
What is the exact question here?

**Comment by chenjianjx** [comment]
There is only a  *.sh file under https://github.com/chenjianjx/swagger2html/tree/master/src/main/bin  , which cannot be run under windows.   

Can you help?

**Comment by dp-la** [comment]
With bash coming to widows 10 (in developer mode now).  It might not be as much of an issue.  Maybe we can try to help though

**Comment by chenjianjx** [comment]
Never mind. I will fix this problem with another issue you mentioned.

**Comment by chenjianjx** [comment]
Fixed in 1.0.7
