### ISSUE TITLE
Styles don't convert well to docx

### ISSUE THREAD

**Issue by dp-la** [chenjianjx/swagger2html#2]
This program is really great.  The only problem we have is that when converting the HTML file to a docx using microsoft word, it doesn't convert very well.  
For PDF the styles convert great.  So to convert to word, I convert to PDF and then to word, but it still doesn't look that great.

Maybe you can have multiple CSS options.

**Comment by chenjianjx** [comment]
How bad is it? can you show me a screenshot of the docx?

**Comment by chenjianjx** [comment]
anyway I will fix this issue per your request, by making css separate.

**Comment by Number1MSFanboy** [comment]
PDF was fine, I tried with word 2013 and word 2016, both looked like:
![testapi](https://cloud.githubusercontent.com/assets/13022236/14435288/fe9815aa-ffcb-11e5-92d4-7acff3e7dbf2.jpg)

**Comment by dp-la** [comment]
The PDF was great, but this is what it looked like on word 2013 and 2016.  Word I think needs a simple css.

![testapi](https://cloud.githubusercontent.com/assets/7052164/14436027/98afc810-ffcf-11e5-90ce-bd45c6a08f4e.jpg)

**Comment by chenjianjx** [comment]
Fixed in 1.0.7.   Please try it.   For guidance, see [here]https://github.com/chenjianjx/swagger2html#customization-of-css
