### ISSUE TITLE
When running on windows cmd I get an error

### ISSUE THREAD

**Issue by dp-la** [chenjianjx/swagger2html#4]
Error: Could not find or load main class org.swagger2html.S2hMain

sorry I haven't used java in a long time, maybe it something simple

**Comment by chenjianjx** [comment]
jdk version must be >= 1.7. 

And how do you run it?  Do you run it in a cmd window or do you just click sh2.bat?

**Comment by danparker276** [comment]
I'm a .net software (sorta) engineer.  I run it on cmd, as administrator on command line, but I"m guessing you have it compiled on your machine, but not on mine.  So I have my co worker usually just run it on their linux machine.  Ally props to you though.  This is the best thing ever..  You have done such a great job, better than the others.

**Comment by odanielfranca** [comment]
I got the same issue here, running in a cmd window
![Screenshot](https://user-images.githubusercontent.com/51707160/60124646-7cebe600-9760-11e9-8fe8-39c82bacfa85.png)

**Comment by chenjianjx** [comment]
> I got the same issue here, running in a cmd window
> ![Screenshot](https://user-images.githubusercontent.com/51707160/60124646-7cebe600-9760-11e9-8fe8-39c82bacfa85.png)

You didn't run Maven to build it.   Please read the instructions in the README more carefully
